"""
Prometheus metrics collector for DeepDefend NIDS.

Exposes operational metrics for monitoring and alerting:
- Packets processed per second
- Flows analyzed per second  
- Alerts generated by severity
- Model inference latency
- False positive tracking
- System resource usage

Metrics are exposed via HTTP endpoint for Prometheus scraping.
"""

import time
import threading
import psutil
import os
from typing import Dict, Optional
from collections import defaultdict
from datetime import datetime

from prometheus_client import (
    Counter, Gauge, Histogram, Summary,
    CollectorRegistry, generate_latest,
    CONTENT_TYPE_LATEST
)
from deepdefend.utils.logging import get_logger

logger = get_logger(__name__)


class MetricsCollector:
    """
    Collect and expose DeepDefend operational metrics.
    
    Metrics categories:
    - Traffic: packets, flows, bytes processed
    - Detection: alerts by class, severity, confidence
    - Performance: inference latency, queue depths
    - System: CPU, memory, uptime
    - Response: blocks executed, notifications sent
    
    All metrics are labeled for multi-dimensional analysis.
    """
    
    def __init__(self, registry: Optional[CollectorRegistry] = None):
        self.registry = registry or CollectorRegistry()
        
        # ─── Traffic Metrics ─────────────────────────────────
        self.packets_processed = Counter(
            'deepdefend_packets_processed_total',
            'Total packets processed',
            registry=self.registry
        )
        
        self.flows_processed = Counter(
            'deepdefend_flows_processed_total',
            'Total flow records processed',
            registry=self.registry
        )
        
        self.bytes_processed = Counter(
            'deepdefend_bytes_processed_total',
            'Total bytes processed',
            registry=self.registry
        )
        
        self.flow_windows_completed = Counter(
            'deepdefend_flow_windows_total',
            'Total flow windows completed',
            registry=self.registry
        )
        
        # ─── Detection Metrics ───────────────────────────────
        self.alerts_total = Counter(
            'deepdefend_alerts_total',
            'Total alerts generated',
            ['severity', 'attack_class', 'source'],
            registry=self.registry
        )
        
        self.anomalies_detected = Counter(
            'deepdefend_anomalies_detected_total',
            'Total anomalies detected by Isolation Forest',
            registry=self.registry
        )
        
        self.snort_alerts = Counter(
            'deepdefend_snort_alerts_total',
            'Total Snort alerts received',
            ['classification'],
            registry=self.registry
        )
        
        self.alert_confidence = Histogram(
            'deepdefend_alert_confidence',
            'Alert confidence distribution',
            buckets=[0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 0.95, 0.99],
            registry=self.registry
        )
        
        self.false_positives = Counter(
            'deepdefend_false_positives_total',
            'Total false positives (requires analyst feedback)',
            ['attack_class'],
            registry=self.registry
        )
        
        self.missed_attacks = Counter(
            'deepdefend_missed_attacks_total',
            'Total missed attacks (requires ground truth)',
            ['attack_class'],
            registry=self.registry
        )
        
        # ─── Performance Metrics ─────────────────────────────
        self.inference_latency = Histogram(
            'deepdefend_inference_latency_seconds',
            'Model inference latency in seconds',
            buckets=[0.001, 0.005, 0.01, 0.025, 0.05, 0.1, 0.25, 0.5, 1.0],
            registry=self.registry
        )
        
        self.inference_batch_size = Histogram(
            'deepdefend_inference_batch_size',
            'Inference batch sizes',
            buckets=[1, 4, 16, 64, 256, 1024],
            registry=self.registry
        )
        
        self.queue_depth = Gauge(
            'deepdefend_queue_depth',
            'Current input queue depth',
            ['queue_name'],
            registry=self.registry
        )
        
        self.queue_drops = Counter(
            'deepdefend_queue_drops_total',
            'Total items dropped from queues',
            ['queue_name'],
            registry=self.registry
        )
        
        # ─── Response Metrics ────────────────────────────────
        self.blocks_executed = Counter(
            'deepdefend_blocks_executed_total',
            'Total IP blocks executed',
            ['severity'],
            registry=self.registry
        )
        
        self.blocks_active = Gauge(
            'deepdefend_blocks_active',
            'Currently active IP blocks',
            registry=self.registry
        )
        
        self.notifications_sent = Counter(
            'deepdefend_notifications_sent_total',
            'Total notifications sent',
            ['channel'],
            registry=self.registry
        )
        
        self.incidents_generated = Counter(
            'deepdefend_incidents_generated_total',
            'Total incident reports generated',
            ['severity'],
            registry=self.registry
        )
        
        # ─── System Metrics ──────────────────────────────────
        self.uptime_seconds = Gauge(
            'deepdefend_uptime_seconds',
            'System uptime in seconds',
            registry=self.registry
        )
        
        self.cpu_usage_percent = Gauge(
            'deepdefend_cpu_usage_percent',
            'CPU usage percentage',
            registry=self.registry
        )
        
        self.memory_usage_bytes = Gauge(
            'deepdefend_memory_usage_bytes',
            'Memory usage in bytes',
            registry=self.registry
        )
        
        self.snort_running = Gauge(
            'deepdefend_snort_running',
            'Snort process running (1=yes, 0=no)',
            registry=self.registry
        )
        
        self.inference_engine_running = Gauge(
            'deepdefend_inference_engine_running',
            'Inference engine running (1=yes, 0=no)',
            registry=self.registry
        )
        
        # ─── State ───────────────────────────────────────────
        self._start_time = time.time()
        self._shutdown = False
        self._system_monitor_thread: Optional[threading.Thread] = None
        
        logger.logger.info("MetricsCollector initialized")
    
    # ─── Record Methods ──────────────────────────────────────
    
    def record_packet(self, size: int = 0):
        """Record a processed packet."""
        self.packets_processed.inc()
        if size:
            self.bytes_processed.inc(size)
    
    def record_flow(self):
        """Record a processed flow record."""
        self.flows_processed.inc()
    
    def record_window_complete(self, flow_count: int):
        """Record a completed flow window."""
        self.flow_windows_completed.inc()
    
    def record_alert(self, severity: str, attack_class: str, 
                     confidence: float, sources: list):
        """Record a detected alert."""
        source_str = "+".join(sorted(sources))
        self.alerts_total.labels(
            severity=severity,
            attack_class=attack_class,
            source=source_str
        ).inc()
        self.alert_confidence.observe(confidence)
    
    def record_anomaly(self):
        """Record an anomaly detection."""
        self.anomalies_detected.inc()
    
    def record_snort_alert(self, classification: str):
        """Record a Snort alert."""
        self.snort_alerts.labels(classification=classification).inc()
    
    def record_inference(self, latency_seconds: float, batch_size: int):
        """Record inference performance."""
        self.inference_latency.observe(latency_seconds)
        self.inference_batch_size.observe(batch_size)
    
    def record_queue_depth(self, queue_name: str, depth: int):
        """Record current queue depth."""
        self.queue_depth.labels(queue_name=queue_name).set(depth)
    
    def record_queue_drop(self, queue_name: str):
        """Record a queue drop."""
        self.queue_drops.labels(queue_name=queue_name).inc()
    
    def record_block(self, severity: str):
        """Record an IP block."""
        self.blocks_executed.labels(severity=severity).inc()
    
    def record_notification(self, channel: str):
        """Record a sent notification."""
        self.notifications_sent.labels(channel=channel).inc()
    
    def record_incident(self, severity: str):
        """Record a generated incident report."""
        self.incidents_generated.labels(severity=severity).inc()
    
    def record_false_positive(self, attack_class: str):
        """Record analyst-confirmed false positive."""
        self.false_positives.labels(attack_class=attack_class).inc()
    
    def record_missed_attack(self, attack_class: str):
        """Record an attack that was missed."""
        self.missed_attacks.labels(attack_class=attack_class).inc()
    
    def set_active_blocks(self, count: int):
        """Set current active block count."""
        self.blocks_active.set(count)
    
    def set_snort_status(self, running: bool):
        """Set Snort running status."""
        self.snort_running.set(1 if running else 0)
    
    def set_inference_status(self, running: bool):
        """Set inference engine running status."""
        self.inference_engine_running.set(1 if running else 0)
    
    # ─── System Monitoring ───────────────────────────────────
    
    def start_system_monitoring(self, interval: float = 15.0):
        """Start background thread to collect system metrics."""
        self._system_monitor_thread = threading.Thread(
            target=self._system_monitor_loop,
            args=(interval,),
            name="system-monitor",
            daemon=True
        )
        self._system_monitor_thread.start()
    
    def _system_monitor_loop(self, interval: float):
        """Periodically collect system metrics."""
        while not self._shutdown:
            try:
                process = psutil.Process(os.getpid())
                
                self.uptime_seconds.set(time.time() - self._start_time)
                self.cpu_usage_percent.set(process.cpu_percent(interval=1.0))
                self.memory_usage_bytes.set(process.memory_info().rss)
                
            except Exception as e:
                logger.logger.error(f"System metrics collection failed: {e}")
            
            time.sleep(interval)
    
    def stop_system_monitoring(self):
        """Stop system monitoring thread."""
        self._shutdown = True
    
    # ─── Metrics Export ──────────────────────────────────────
    
    def get_metrics(self) -> bytes:
        """Get Prometheus metrics in exposition format."""
        return generate_latest(self.registry)
    
    def get_metrics_text(self) -> str:
        """Get metrics as text string."""
        return generate_latest(self.registry).decode('utf-8')
    
    def get_summary(self) -> Dict:
        """Get a human-readable metrics summary."""
        return {
            "uptime_seconds": time.time() - self._start_time,
            "packets_processed": self.packets_processed._value.get(),
            "flows_processed": self.flows_processed._value.get(),
            "alerts_total": sum(
                self.alerts_total.labels(severity=s, attack_class=a, source=sc)._value.get()
                for s in ["critical", "high", "medium", "low"]
                for a in ["dos", "probe", "r2l", "u2r", "unknown"]
                for sc in ["snort", "anomaly_ml", "snort+anomaly_ml"]
            ) if hasattr(self.alerts_total, '_metrics') else 0,
            "blocks_active": self.blocks_active._value.get(),
            "snort_running": bool(self.snort_running._value.get()),
            "cpu_percent": self.cpu_usage_percent._value.get(),
            "memory_mb": self.memory_usage_bytes._value.get() / (1024 * 1024),
        }